### ISSUE TITLE
Function to send other notification from the autor after the first notification

### ISSUE THREAD

**Issue by Galman21** [jlvandenhout/iota_streams_experience#1]
More than an issue this is a request of help.

I used author.rs and it correctly created the channel and sent the first notification, in fact i can receive it (as visibile below)

![1](https://user-images.githubusercontent.com/34507560/120347968-074e0480-c2fd-11eb-8405-6e235b8e2418.png)

After, i wrote sendsuccessive.rs file (here [sendsuccessive.txt](https://github.com/jlvandenhout/iota-streams-experience/files/6577366/sendsuccessive.txt)) with the aim of send a second notification (always by the author of the channel) but i obtaines the following error.

![2](https://user-images.githubusercontent.com/34507560/120348338-601d9d00-c2fd-11eb-8716-bdb4b24f7f90.png)

PS: i also used the indexing package to obtain the message index and verified myself that the message is on the testnet's tangle.

**Comment by jlvandenhout** [comment]
I think the problem here is the Author state. Streams works by updating a cryptographic sponge state under the hood to handle messages correctly.

In your second run of the script where you commented out the announcement part, the Author state is initialized again but this time never updated with the announcement and probably misses information to handle the stream. To confirm this you can try either of two things:

- Send the second notification right after the first in the same script where you announce the channel.

- Persist the Author state between running the first and the second script. You can use the `export` and `import` methods of the Author to serialize and deserialize the state to store it somewhere.

**Comment by jlvandenhout** [comment]
Could you checkout the branch of #2 and see if that clears things up? Any suggestions or further questions are welcome!
